import assert from "node:assert/strict";
import { test } from "node:test";
import { ec, shortString } from "starknet";
import { MODE } from "./constants.js";
import { generateEnvelopeKey } from "./keys.js";
import { releaseMessageHash, signRelease } from "./message.js";

/**
 * Generated by `release_message_hash_is_stable` in the Cairo suite
 * (`cairo/src/tests/envelope_test.cairo`). Regenerate with:
 *
 *   cd cairo && snforge test release_message_hash_is_stable
 *
 * If this test fails, the SDK and the deployed contract disagree about what is
 * being signed, and every signature the SDK produces will be rejected on-chain.
 */
const CAIRO_VECTOR =
  864871185401224514201628893549155396398372124344896425622127250497623408572n;

test("message construction matches the Cairo contract", () => {
  const hash = releaseMessageHash({
    anonymizer: shortString.encodeShortString("CONTRACT"),
    mode: MODE.note,
    claimPublicKey: shortString.encodeShortString("PUBKEY"),
    target: shortString.encodeShortString("TARGET"),
  });

  assert.equal(BigInt(hash), CAIRO_VECTOR);
});

test("each release mode produces a distinct message", () => {
  const common = {
    anonymizer: "0x1",
    claimPublicKey: "0x2",
    target: "0x3",
  };

  const hashes = new Set(
    Object.values(MODE).map((mode) => releaseMessageHash({ ...common, mode })),
  );

  assert.equal(
    hashes.size,
    Object.values(MODE).length,
    "modes must not collide, or an authorisation for one path would work on another",
  );
});

/** `(r, s)` as the 128-hex-character compact form `starkCurve.verify` takes. */
function compact({ r, s }: { r: string; s: string }): string {
  const pad = (value: string) => BigInt(value).toString(16).padStart(64, "0");
  return pad(r) + pad(s);
}

test("a signature does not verify against a different target", () => {
  const key = generateEnvelopeKey();
  const message = {
    anonymizer: "0x1",
    mode: MODE.address,
    claimPublicKey: key.publicKey,
    target: "0xa11ce",
  };

  const signature = compact(signRelease(key.privateKey, message));
  // Cairo's `check_ecdsa_signature` takes the stark key (the x coordinate),
  // which is what the contract stores as the envelope id. Verifying off-chain
  // needs the full curve point.
  const fullPublicKey = ec.starkCurve.getPublicKey(key.privateKey);

  assert.ok(
    ec.starkCurve.verify(signature, releaseMessageHash(message), fullPublicKey),
    "should verify against the target it was signed for",
  );
  assert.ok(
    !ec.starkCurve.verify(
      signature,
      releaseMessageHash({ ...message, target: "0xbad" }),
      fullPublicKey,
    ),
    "a front-runner swapping in their own recipient must invalidate it",
  );
});
